### PR TITLE
Update for Swift 3.0

### PR DESCRIPTION
**Pull request by jordanekay**

### CODE REVIEW

**Comment by tiferrei** [comment]
Thanks for this @jordanekay! Meanwhile the repo owner doesn't merge this, can I point my CocoaPods source to your fork?

**Comment by jrendel** [comment]
@tiferrei I have not merged this in yet as Swift 3.0 is still only available in beta builds and there are currently active users of the develop branch that are still focused on Swift 2.2.

In addition, I have been making changes to the library in my develop branch and would need to review the changes in this pull to make sure everything is accounted for.  When I can, I will do so and most likely move all these changes into a Swift 3.0 branch until it leaves beta.

**Comment by tiferrei** [comment]
Well yes, but wouldn't it be easier to merge it into a `swift3` branch and then just apply the new changes via a rebase as you add them to the `develop` branch? With small reviews for comparabilities with swift 3

**Comment by cihadhoruzoglu** [comment]
Swift 3 is now available, when this pull request will be merged?

**Comment by jrendel** [comment]
@cihadhoruzoglu The latest version in master and in cocoa pods is v 3.0 of this library and includes Swift 3.0 support. I didn't merge this pull request in directly as it conflicted with my changes I had been working on, and there were a couple things I wanted to do slightly differently.

**Pull request closed without merging**
