### PR TITLE
Add support for Swift Package Manager

### PR DESCRIPTION
**Pull request by adincebic**
I have added package.swift file to support SPM.
Note that I did not specify minimum platform version as it is iOS 8 by default.

### CODE REVIEW

**Comment by mateuszjablonski** [comment]
@jrendel is there any possibility this will be merged soon? My project depends on it.

**Comment by adincebic** [comment]
You can use my fork until this gets merged.

**Comment by jimisaacs** [comment]
@jrendel please merge this

**Comment by thejeff77** [comment]
@jrendel thanks for taking a look at this - a merge would be awesome.

**Comment by thejeff77** [comment]
@adincebic - As this impacts all users, updating the README would go along nicely with this PR, and will likely increase the chances of @jrendel merging this sooner.

**Comment by mattmaddux** [comment]
I added a new PR (#149) that includes updates to the README (as well as a tests target). At first I didn't see the TWO other PRs adding SPM and removed mine once I did. But decided to reopen after reading the comment above from @thejeff77.

**Comment by jrendel** [comment]
Sorry I haven't kept up with the repo guys, but I've now merged in one of the other Swift Package Manager PRs, so I'm going to close this one.

**Pull request closed without merging**
