### PR TITLE
Add kSecAttrAccessGroup to allow Keychain Sharing usage

### LINKED ISSUE #7: Keychain access group
Can you add support for saving to a specific keychain access group? This way we can share the keychain between multiple apps and/or extensions.

### PR DESCRIPTION
**Pull request by AndreasBoehm**
Hi Jason,

im working on a today extension for my app so i needed keychain sharing and did some changes on your KeychainWrapper to allow this. Fixes #7 

Best,
Andreas

### CODE REVIEW

**Comment by AndreasBoehm** [comment]
I tried to add tests that really test the usage of the identifier, but i am unable to do this because i allways get a "errSecNoAccessForItem (-25243)" error trying to use "hasValueForKey()". 

This happens because Keychain Sharing is not enabled when the tests are run.

**Comment by jrendel** [comment]
Thanks Andreas! I'll play around with unit tests a bit and see if I can find anything that might help as well with testing this more fully.

**Comment by jrendel** [comment]
Oops didn't mean to close this. Andreas I found a way to check for the iOS simulator in Swift so I can at least check in KeychainWrapper if running on the simulator and not add the access group. From what I've read, on the simulator you have access to all groups so the access group is irrelevant on the simulator. But if you do set it, Adding and Updating items will fail.

I added a couple unit tests to confirm that this is working. This allows you to build an app that uses access groups for keychain access and run it on the simulator. However, this does not let you test that access groups are working properly. I am going to have to do that in a test app running on a device.

**Comment by jrendel** [comment]
I've not done a true test with 2 different apps yet, but I did update my example project to show it working with the new access group: https://github.com/jrendel/SwiftKeychainWrapperExample

**Comment by AndreasBoehm** [comment]
I checked your changes to not use the access group when the app runs on simulator.
If i run the app on the simulator all is working fine with usage of the access group (without your simulator check to disable it) so for me i only got these error when i run the tests. Maybe it works for my application because i already have all this signing stuff setup and so also the app that runs on my simulator is signed?

so in my opinion disabling access group on the simulator is not exactly right.

**Comment by jrendel** [comment]
If thats the case, then I agree with you. It didn't work for me on the simulator when I first tested it, and then a quick search showed it gave errors for others on the simulator as well. So I will need to retest this at home. I may have had my access groups setup incorrectly when I first tested on the simulator, as I made a few changes before testing on the device. 

When I get home today I'll test again on the test application I've got setup. It has all the provisioning setup correctly now to run on the device, so may work in the simulator as well as you've described.

**Comment by jrendel** [comment]
I've confirmed this is correct. Once provisioned correctly, it works fine on the simulator even if you enter an access group. So I removed the simulator check all together.

The question still remains of how to do proper unit tests and I haven't started digging too deep into what options there may be yet.

**Pull request merged**
