### PR TITLE
Add SwiftPM support

### PR DESCRIPTION
**Pull request by netizen01**

### CODE REVIEW

**Comment by munirwanis** [comment]
@jrendel Will this be supported?

**Comment by reshadf** [comment]
would love to have this merged!

**Comment by p-nicolaou** [comment]
Shall we start worrying about @jrendel ?

**Comment by nihilias** [comment]
Hey @jrendel you still there? We could use your ownership here 🤗

**Comment by jrendel** [comment]
Sorry I haven't kept up with the repo guys, but I've now merged in one of the other Swift Package Manager PRs, so I'm going to close this one.

**Pull request closed without merging**
